### ISSUE TITLE
Menu sometimes overlaps

### ISSUE THREAD

**Issue by Glurt** [shehabic/Droppy#10]
Is there a way to specify an offset?

![screen shot 2015-04-27 at 16 04 38](https://cloud.githubusercontent.com/assets/4775537/7350463/4ce9851a-ecf7-11e4-91fe-8c2df0e7dd25.png)

**Comment by shehabic** [comment]
Sure: you can style it the way you want as in here:

https://github.com/shehabic/Droppy#customizing-syles

**Comment by Glurt** [comment]
I'm talking about the distance between the anchor button and the popup menu. I know its difficult to see with it being black but the menu is overlapping the button icon.

Here's what it's supposed to look like. This is occurring on a Nexus 7.

![image](https://cloud.githubusercontent.com/assets/4775537/7353845/8fe73224-ed0e-11e4-8801-791ba51a7d9c.png)

**Comment by shehabic** [comment]
ok, I haven't tried this (it's in the coded, needs to be dynamic) but can you try adding margins to 
"DroppyPopup" style ?

**Comment by shehabic** [comment]
With the last version with scroll support, non of this should happen
