### ISSUE TITLE
With many items added some are not shown

### ISSUE THREAD

**Issue by lupajz** [shehabic/Droppy#11]
I am trying to create a simple month picker with this lib. I just want to show dropdown of 12 month names from top of the screen but I can only see months from January to October, rest of the are missing. Can there be a option to wrap the dropdown view in scroll view or something like that so I can get access to rest of the options from dropdown menu ? Also it would be conviniet to have an onClickCallback that would return position of item.

**Comment by Mohamed-Shehab** [comment]
Well, sure this is quite important, probably should be there in the next release (I'd say, this weekend)

**Comment by shehabic** [comment]
Well, sure this is quite important, probably should be there in the next release (I'd say, this weekend)

Regarding the position: by default if you don't specify ids it generates numerical id from 0 to (n-1)

**Comment by lupajz** [comment]
Okay  :+1: already excited

I didn't realise that position, thank you.

**Comment by shehabic** [comment]
Hey lupajz,

The approach I did for adding a scroll view didn't work very well, it's wrapping the heigh to a too small value, probably will have to calculate the max. possible visible height for the whole popup to calculate the scrollable area correctly, It'll take a bit longer time

**Comment by shehabic** [comment]
Sorry closed by mistake

**Comment by AdonayP** [comment]
Waiting for this enhancement, some items are now shown in the dropdown :(

**Comment by shehabic** [comment]
Sorry I have been traveling for sometime, now I'll resume working on this lib. soon.

**Comment by azizimusa** [comment]
Same problem too. No scrollview for long data.

**Comment by azizimusa** [comment]
I can't understand what you say about position on https://github.com/shehabic/Droppy/issues/11#issuecomment-99803767 

Can you explain it a bit more?

**Comment by shehabic** [comment]
Added scroll support
