### ISSUE TITLE
local use?

### ISSUE THREAD

**Issue by TheLoyalCruel** [shehabic/Droppy#12]
hi!
how to use your library completely locally in my project?

**Comment by Mohamed-Shehab** [comment]
What do you mean by completely locally ?

**Comment by TheLoyalCruel** [comment]
I mean without using this gradle:
compile 'com.shehabic.droppy:Droppy:0.2.5.1@aar'
I want to use your library locally in my project!

another question:
droppyBuilder.addMenuItem(new DroppyMenuItem("test3", R.drawable.ic_launcher));
it does not show icon in list! why?

**Comment by shehabic** [comment]
for your last question, I just pushed the fix for this in v. 2.5.2, 
for the 1st part you can use it locally just clone and use it as a module just like in the samples.
