### ISSUE TITLE
Can't use multiple droppy with diffrent themes ?

### ISSUE THREAD

**Issue by mlounge004** [shehabic/Droppy#17]
Hi Is it possible to use multiple droppy in same app with different styles ?
Thanks for the great lib !

**Comment by mlounge004** [comment]
there should be a way to change height,width,background and text colors through code,on my way to implement that :)

**Comment by Mohamed-Shehab** [comment]
```
there should be a way to change height,width,background and text colors before building doppy menu through code,on my way to implement that :)
```
You can do that of course using custom menu items.

**Comment by mlounge004** [comment]
thanks that worked !
