### ISSUE TITLE
dismiss() crash

### ISSUE THREAD

**Issue by gintechsystems** [shehabic/Droppy#23]
If you tap on the button that shows the dropdown menu over and over and say the user hits the back button to leave the current activity / fragment, it will crash. I am using Lollipop (API Level 22) Here is what I am seeing:

10-01 20:16:18.658  18836-18836/com.droid.visneta W/System.err﹕ java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at com.shehabic.droppy.DroppyMenuPopup.dismiss(DroppyMenuPopup.java:119)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at com.droid.visneta.NetworkQueueActivity.onDestroy(NetworkQueueActivity.java:154)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at android.support.v4.app.Fragment.performDestroy(Fragment.java:2182)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1157)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1304)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:708)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1572)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:493)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:739)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5254)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
10-01 20:16:18.659  18836-18836/com.droid.visneta W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by shehabic** [comment]
this is based on the action action in your code, that's being triggered when the menu is clicked, has nothing to do with the drop-down itself .

**Comment by gintechsystems** [comment]
Actually even when I don't do a menu click I still get an error after testing it for awhile.

**Comment by shehabic** [comment]
hmm.. you mean when trying to remove the menu when the fragment is gone, well catching the back button in the whole activity through a widget is quite hard, alternatively you can add the appropriate code to correctly hide the menu before the fragment is destroyed or on back button tapped

**Comment by gintechsystems** [comment]
Here is the stackstace when I leave the fragment without even clicking the menu:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at com.shehabic.droppy.DroppyMenuPopup.dismiss(DroppyMenuPopup.java:119)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at com.droid.visneta.NetworkQueueActivity.onDestroy(NetworkQueueActivity.java:154)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at android.support.v4.app.Fragment.performDestroy(Fragment.java:2182)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1157)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1304)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:708)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1572)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:493)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at android.os.Looper.loop(Looper.java:135)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-07 08:29:53.024 15477-15477/com.droid.visneta W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
10-07 08:29:53.025 15477-15477/com.droid.visneta W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by gintechsystems** [comment]
Do you have example code for that? Been trying to figure that out but nothing seems to be working, thanks.

**Comment by shehabic** [comment]
Something like this:
```Java
DroppyMenuPopup droppyMeny;
.
.
.
// On your back button trigger this: 
droppyMenu.hide();
```

**Comment by gintechsystems** [comment]
you mean droppyMenu.dismiss() since hide() is not an option.

**Comment by shehabic** [comment]
fixed.

**Comment by gintechsystems** [comment]
Still crashes for me using 5.0

**Comment by gintechsystems** [comment]
I worked around it and fixed myself in october, I can create a pull request later.

**Comment by wangbourne** [comment]
it seems that this change hasn't been included into com.shehabic.droppy:Droppy:0.5.1@aar', right?

at least, i could not find a method of "dismiss"
