### ISSUE TITLE
allowBackup is throwing error. Can you make it false.

### ISSUE THREAD

**Issue by raviteja06** [shehabic/Droppy#27]
>Error:Execution failed for task ':app:processInternalConfigDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:36:9-36
	is also present at [com.shehabic.droppy:Droppy:0.2.5.2] AndroidManifest.xml:12:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:34:5-101:19 to override.

**Comment by shehabic** [comment]
Fixed
