### ISSUE TITLE
How to change the color of the separator?

### ISSUE THREAD

**Issue by j4ques** [shehabic/Droppy#28]
Hello,

is it possible to create a separator via XML Resource file?
As I did not succeed in doing this via XML, I managed to do it via code (like in your example). 
Somehow I was not able to change the color of the divider. 
Could you give me a hint? 

I tried this in styles.xml

`item name="droppyMenuSeparatorStyle">@style/My.Custom.Divider</item>
...
<style name="My.Custom.Divider" parent="Droppy.DroppyMenuSeparator">
        <item name="android:background">@drawable/droppy_separator</item>
        <item name="android:layout_height">0.5dp</item>
        <item name="android:layout_width">match_parent</item>
        <item name="android:orientation">horizontal</item>
    </style>`

and droppy_separator.xml:

`<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="@color/c_green"/>
</shape>`

**Comment by shehabic** [comment]
there's a bug, I just fixed, expect it to be there in 2-3 hours, I'll also update the lib. with some useful features that people added in some forks of the lib.

**Comment by shehabic** [comment]
This is fixed in version 0.5.0 currently updated here, will be available on maven's central shortly (I'd say 1 hr)

**Comment by shehabic** [comment]
it's available right now:
http://search.maven.org/#artifactdetails|com.shehabic.droppy|Droppy|0.5.0|aar.asc
