### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Euphrates-Media** [shehabic/Droppy#3]
When I try to add Droppy in gradle, it errors:

Error:Module version com.shehabic.droppy:Droppy:0.2.1 depends on libraries but is not a library itself

**Comment by shehabic** [comment]
Can you please post your gradle code here ?

**Comment by shehabic** [comment]
Please also make sure your have MavenCentral in your repositories as the lib is hosted on Maven
```groovy
repositories {
        mavenCentral()
}
```

**Comment by shehabic** [comment]
I think it's fixed by this change as per tests too
