### ISSUE TITLE
Error:(128, 0) No such property: sonatypeRepo for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

### ISSUE THREAD

**Issue by MustafaAdil** [shehabic/Droppy#30]
I've just imported this library in empty project and it gives the following error in library\build.gradle:

**Error:(128, 0) No such property: sonatypeRepo for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer**

how to solve this?

**Comment by shehabic** [comment]
don't run this task, it's something that I use to upload to sonatype, I'll remove it from the lib. but you don't need to build the lib. manually, use it directly from maven

**Comment by shehabic** [comment]
if you need to build it locally remove everything past this line: https://github.com/shehabic/Droppy/blob/master/library/build.gradle#L86

**Comment by MustafaAdil** [comment]
yes its fine now.. Thanks!
