### ISSUE TITLE
Start Scale Animation from to Top to Bottom.

### ISSUE THREAD

**Issue by MustafaAdil** [shehabic/Droppy#31]
when clicked on button 3, I want to start the animation from top to bottom but its not happening. Here is what I'm doing:

    @Override
    public void animateShow(final DroppyMenuPopupView popup, final View anchor)
    {
       
        //ScaleAnimation scaleAnimation = new ScaleAnimation(0f, 1f, 0f, 1f, Animation.RELATIVE_TO_SELF, 0.25f, Animation.RELATIVE_TO_SELF, 1f);
        Animation scaleAnimation = new ScaleAnimation(
                Animation.RELATIVE_TO_SELF,
                0.0f,
                Animation.RELATIVE_TO_SELF,
                0.0f,
                Animation.RELATIVE_TO_SELF,
                0.0f,
                Animation.RELATIVE_TO_SELF,
                5.2f);
        scaleAnimation.setDuration(ANIMATION_DURATION);
        scaleAnimation.setFillAfter(true);
        popup.startAnimation(scaleAnimation);
    }

**Comment by shehabic** [comment]
Well, this have nothing to do with the library itself, but I'll to provide some info, 
first I'd highly recommend if you check the ScaleAnimation reference and which parameters in which sequence do what, here's Android's Source code.

http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.4.4_r1/android/view/animation/ScaleAnimation.java#Animation

if you change the very last parameter of my original example from 1f to 0f, it'll do what you want.

ScaleAnimation scaleAnimation = new ScaleAnimation(0f, 1f, 0f, 1f, Animation.RELATIVE_TO_SELF, 0.25f, Animation.RELATIVE_TO_SELF, 0f);
