### ISSUE TITLE
Drop down alignment problem 

### ISSUE THREAD

**Issue by MustafaAdil** [shehabic/Droppy#32]
When I click on the button, the drop down is not aligned with the button properly, here is the screenshot:

![handy](https://cloud.githubusercontent.com/assets/17173766/13428070/cf833360-dfd9-11e5-8a03-3b9433f07bcb.jpg)

**Comment by shehabic** [comment]
Please share more info about the code / XML of this layout, and how you're using it.

**Comment by MustafaAdil** [comment]
**Button's** xml is:

      <info.hoang8f.widget.FButton
        android:id="@+id/choose_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:minHeight="50dp"
        android:minWidth="110dp"
        android:paddingLeft="25dp"
        android:paddingRight="20dp"
        android:paddingTop="-5dp"
        android:gravity="center"
        android:text="Choose Category"
        android:textColor="@android:color/white"
        fbutton:cornerRadius="6dp"
        fbutton:shadowEnabled="true"
        fbutton:shadowHeight="4dp"
        android:layout_marginTop="24dp"
        fbutton:buttonColor="#e73c3a"
        android:textSize="13sp"
        android:layout_alignParentTop="true"
        android:layout_centerHorizontal="true" />

I'm using a flat button library for buttons. Here is the **code** for button in activity:

       Button chooseBtn = (Button) findViewById(R.id.choose_button);
        chooseBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                droppyMenu(chooseBtn);
            }
        });

     public void droppyMenu(Button btn)
    {

        DroppyMenuPopup.Builder droppyBuilder = new DroppyMenuPopup.Builder(this, btn);
        DroppyMenuPopup droppyMenu = droppyBuilder.fromMenu(R.menu.categories_list)
                .triggerOnAnchorClick(false)
                .setOnClick(this)
                .setOnDismissCallback(this)
                .setPopupAnimation(new DroppyScaleAnimation())
                .build();
        droppyMenu.show();

    }

I've also tried replacing the **FButton** with just normal button but the error is still the same

**Comment by AbdulSamadQureshi** [comment]
I have a similar problem, i am adding y offset but no matter what value i set for it, it has no effect at all, surprisingly the x-offset works fine. Any guide to this problem?

**Comment by sahilgarg1993** [comment]
I'm having similar kind of problem. In Lollipop, Popup menu is overlapping the button. But in pre lollipop it is working fine.

**Comment by deepakcipl** [comment]
Try this.. It is working in my case 
        final DroppyMenuPopup build = dropBuilder.fromMenu(R.menu.drop_menu)
                .setOnClick(this)
                .triggerOnAnchorClick(true)
                .setPopupAnimation(new DroppyFadeInAnimation())
                .setYOffset(-100)
                .build();

**Comment by henengel** [comment]
Any solution to this issue?
I'm having the same exact issue and trying the solution suggested in the last comment didn't solve it.
