### ISSUE TITLE
How do i populate dynamic menus?

### ISSUE THREAD

**Issue by spurdow** [shehabic/Droppy#33]
I have a radio button which when i select , it should change the droppy menu to other menu. I got 2 states of menus.

How do i mitigate this?

**Comment by shehabic** [comment]
if you mean within the same menu, you should use just 1 item with your own View and do the logic normally there so the menu will be just a popup,
if this radio is completely outside of your drop down then just create 2 different menus like in the Sample project, where there are 3 menus in the same Screen, just set the target of 2 of them to the same Clickable View.
