### ISSUE TITLE
The top-position Error.

### ISSUE THREAD

**Issue by cabatte** [shehabic/Droppy#4]
The top-position of the Popup is not correct when used with a visible ActionBar

**Comment by cabatte** [comment]
Hi, have any workarround for this problem?

**Comment by shehabic** [comment]
I tested this and couldn't reproduce on any version of android, I'm not sure if it's still there or not

**Comment by cabatte** [comment]
Ok thanks.

Em seg, 27 de abr de 2015 06:55, Mohamed Shehab <notifications@github.com>
escreveu:

**Comment by shehabic** [comment]
Added a new way to calculate the dimensions and position.
