### ISSUE TITLE
The specified child already has a parent

### ISSUE THREAD

**Issue by ppamorim** [shehabic/Droppy#6]
The specified child already has a parent. You must call removeView() on the child's parent first.

**Comment by shehabic** [comment]
This happens when you try to add a custom view, that's already visible/inflated, the work-around is to add it as resource i.e. ```R.layout.your_custom_layout``` but I'll add an extra thing to the lib to detach the view from its parent first before attaching to the popup menu

**Comment by Euphrates-Media** [comment]
I am not using custom view and has same problem, seems I should find another drop down menu :(

**Comment by shehabic** [comment]
can you share your setup here please?

**Comment by shehabic** [comment]
I believe with the new release this issue should be fixed, do you guys have any feedback or still facing this issue ?

**Comment by mjtrujill** [comment]
Your latest updates have solved my issue.  I have this set up in a listview, so i have multiple buttons that can open a popup.  The use case that was crashing my app would happen if I opened a popup from one item, then click outside the window or open popup from another item, then tried to open the original popup again.  With the update, I have no issues.

**Comment by Mohamed-Shehab** [comment]
I'm closing this issue, please if anynone's still facing an issue ask for reopening or open a new one with details.

**Comment by shehabic** [comment]
I'm closing this issue, please if anynone's still facing an issue ask for reopening or open a new one with details.
